# Generated by Django 4.2 on 2023-06-18 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tienda.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0016_auto_20210705_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agengar_horas_disponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(help_text='Servicio: (Vacunas, Peluqueria, ChequeoMedico)', max_length=200)),
                ('dia', models.DateField(help_text='Ingrese el día', validators=[tienda.models.validar_dia])),
                ('hora', models.TimeField(help_text='Ingrese la hora')),
            ],
            options={
                'unique_together': {('hora', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrucel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='carucel')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('comentario', models.TextField()),
                ('rating', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('Perro (a)', 'Perro (a)'), ('Gato (a)', 'Gato (a)')], default='PERRO(A)', max_length=10)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='MACHO', max_length=8)),
                ('raza', models.CharField(blank=True, max_length=60, null=True)),
                ('microchip', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=8)),
                ('foto', models.ImageField(upload_to='mascota')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedirHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.agengar_horas_disponibles')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.mascota')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_pedidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='oferta',
            new_name='tendencia',
        ),
        migrations.AddField(
            model_name='categorias',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='categoria'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.categorias'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=800),
        ),
        migrations.DeleteModel(
            name='datosEnvio',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='favorito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.productos'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tienda.productos'),
        ),
        migrations.AddField(
            model_name='carro',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.productos'),
        ),
        migrations.AddField(
            model_name='carro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
