# Generated by Django 4.2 on 2023-06-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_alter_productos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('subtitulo', models.CharField(max_length=500)),
                ('historia', models.TextField()),
                ('foto_doctora', models.ImageField(upload_to='nosotros')),
                ('servicio1', models.CharField(max_length=500)),
                ('descripcion1', models.TextField()),
                ('imagen1', models.ImageField(upload_to='nosotros')),
                ('servicio2', models.CharField(max_length=500)),
                ('descripcion2', models.TextField()),
                ('imagen2', models.ImageField(upload_to='nosotros')),
                ('servicio3', models.CharField(max_length=500)),
                ('descripcion3', models.TextField()),
                ('imagen3', models.ImageField(upload_to='nosotros')),
                ('servicio4', models.CharField(max_length=500)),
                ('descripcion4', models.TextField()),
                ('imagen4', models.ImageField(upload_to='nosotros')),
                ('servicio5', models.CharField(max_length=500)),
                ('descripcion5', models.TextField()),
                ('imagen5', models.ImageField(upload_to='nosotros')),
                ('servicio6', models.CharField(max_length=500)),
                ('descripcion6', models.TextField()),
                ('imagen6', models.ImageField(upload_to='nosotros')),
                ('vision', models.TextField()),
                ('mision', models.TextField()),
            ],
        ),
    ]
